version: '3.8'

services:
  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"  # Exposing the gateway service on port 8080
    depends_on:
      - frontend
      - backend
      - data_analysis
    networks:
      - llms_network

  frontend:
    build: ./services/frontend
    ports:
      - "3000:80"  # Exposing the frontend service (React app)
    networks:
      - llms_network

  backend:
    build: ./services/backend
    ports:
      - "8000:8000"  # Exposing the backend service (FastAPI)
    networks:
      - llms_network

  database:
    build: ./services/database
    volumes:
      - ./services/database/data:/app/data  # Persisting database files
    networks:
      - llms_network

  data_analysis:
    build: ./services/data_analysis
    ports:
      - "8500:8500"  # If you want to expose the data analysis service directly
    networks:
      - llms_network

networks:
  llms_network:
    driver: bridge
